title: JSON BinPack
email: hello@sourcemeta.com
description: A space-efficient open-source binary JSON serialization format based on JSON Schema
baseurl: ""
url: "https://jsonbinpack.sourcemeta.com"
repository: https://github.com/sourcemeta/jsonbinpack
markdown: kramdown
collections:
  docs:
    output: true
    permalink: /docs/:path
sass:
  style: :compressed
  sass_dir: .
plausible:
  domain: jsonbinpack.sourcemeta.com
twitter:
  url: https://twitter.com/sourcemeta

sendinblue:
  form:
    email:
      id: EMAIL
    optin:
      id: OPT_IN
    action: "https://da18022d.sibforms.com/serve/MUIEAHu4VPI_MnP4bwvlnO27StjQXiqIdIg5KGMXssM2E6UB9XtOkK8bTddkkmgyfdW3yt9j8rJbDboThJGYRInIivstyFAFEcwfVbad9MSBzRAGPX9Iz4rxhsuqfNQucdlaU34uqIJlSwCJhxAtT9yVqyoFXuDB8nbS4hGi1sZeMgcaWIVCQjwH85S70gX-Vvu5A7N3LSZ9W-PE"
